# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ftMixer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1280, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(12)
        self.centralwidget.setFont(font)
        self.centralwidget.setStyleSheet("QWidget {\n"
"    background-color: rgb(227, 248, 250);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.inputPart = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputPart.sizePolicy().hasHeightForWidth())
        self.inputPart.setSizePolicy(sizePolicy)
        self.inputPart.setMinimumSize(QtCore.QSize(800, 0))
        self.inputPart.setMaximumSize(QtCore.QSize(600000, 16777215))
        self.inputPart.setStyleSheet("QWidget#inputPart {\n"
"    border: 2px dashed #26c6da;\n"
"    border-radius: 10px;\n"
"    padding: 1px 18px 1px 3px;\n"
"}\n"
"")
        self.inputPart.setObjectName("inputPart")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.inputPart)
        self.verticalLayout.setObjectName("verticalLayout")
        self.imgBlock01and02 = QtWidgets.QWidget(self.inputPart)
        self.imgBlock01and02.setObjectName("imgBlock01and02")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.imgBlock01and02)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.imgBlock01 = QtWidgets.QWidget(self.imgBlock01and02)
        self.imgBlock01.setStyleSheet("QWidget {\n"
"    background-color: rgb(140, 225, 235);\n"
"}\n"
"")
        self.imgBlock01.setObjectName("imgBlock01")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.imgBlock01)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.img01 = QtWidgets.QFrame(self.imgBlock01)
        self.img01.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.img01.setFrameShadow(QtWidgets.QFrame.Raised)
        self.img01.setObjectName("img01")
        self.horizontalLayout.addWidget(self.img01)
        self.fourierT01 = QtWidgets.QFrame(self.imgBlock01)
        self.fourierT01.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fourierT01.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fourierT01.setObjectName("fourierT01")
        self.horizontalLayout.addWidget(self.fourierT01)
        self.horizontalLayout_6.addWidget(self.imgBlock01)
        self.imageBlock02 = QtWidgets.QWidget(self.imgBlock01and02)
        self.imageBlock02.setStyleSheet("QWidget {\n"
"    background-color: rgb(140, 225, 235);\n"
"}")
        self.imageBlock02.setObjectName("imageBlock02")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.imageBlock02)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.img02 = QtWidgets.QFrame(self.imageBlock02)
        self.img02.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.img02.setFrameShadow(QtWidgets.QFrame.Raised)
        self.img02.setObjectName("img02")
        self.horizontalLayout_2.addWidget(self.img02)
        self.fourierT02 = QtWidgets.QFrame(self.imageBlock02)
        self.fourierT02.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fourierT02.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fourierT02.setObjectName("fourierT02")
        self.horizontalLayout_2.addWidget(self.fourierT02)
        self.horizontalLayout_6.addWidget(self.imageBlock02)
        self.verticalLayout.addWidget(self.imgBlock01and02)
        self.imgBlock03and04 = QtWidgets.QWidget(self.inputPart)
        self.imgBlock03and04.setObjectName("imgBlock03and04")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.imgBlock03and04)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.imageBlock03 = QtWidgets.QWidget(self.imgBlock03and04)
        self.imageBlock03.setStyleSheet("QWidget {\n"
"    background-color: rgb(140, 225, 235);\n"
"}")
        self.imageBlock03.setObjectName("imageBlock03")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.imageBlock03)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.fourierT03 = QtWidgets.QFrame(self.imageBlock03)
        self.fourierT03.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fourierT03.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fourierT03.setObjectName("fourierT03")
        self.horizontalLayout_3.addWidget(self.fourierT03)
        self.img03 = QtWidgets.QFrame(self.imageBlock03)
        self.img03.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.img03.setFrameShadow(QtWidgets.QFrame.Raised)
        self.img03.setObjectName("img03")
        self.horizontalLayout_3.addWidget(self.img03)
        self.horizontalLayout_5.addWidget(self.imageBlock03)
        self.imageBlock04 = QtWidgets.QWidget(self.imgBlock03and04)
        self.imageBlock04.setStyleSheet("QWidget {\n"
"    background-color: rgb(140, 225, 235);\n"
"}")
        self.imageBlock04.setObjectName("imageBlock04")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.imageBlock04)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.img04 = QtWidgets.QFrame(self.imageBlock04)
        self.img04.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.img04.setFrameShadow(QtWidgets.QFrame.Raised)
        self.img04.setObjectName("img04")
        self.horizontalLayout_4.addWidget(self.img04)
        self.fourierT04 = QtWidgets.QFrame(self.imageBlock04)
        self.fourierT04.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fourierT04.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fourierT04.setObjectName("fourierT04")
        self.horizontalLayout_4.addWidget(self.fourierT04)
        self.horizontalLayout_5.addWidget(self.imageBlock04)
        self.verticalLayout.addWidget(self.imgBlock03and04)
        self.horizontalLayout_11.addWidget(self.inputPart)
        self.outputPart = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputPart.sizePolicy().hasHeightForWidth())
        self.outputPart.setSizePolicy(sizePolicy)
        self.outputPart.setMinimumSize(QtCore.QSize(400, 600))
        self.outputPart.setMaximumSize(QtCore.QSize(326, 16777215))
        self.outputPart.setStyleSheet("QWidget#outputPart {\n"
"    border: 2px dashed #26c6da;\n"
"    border-radius: 10px;\n"
"    padding: 1px 18px 1px 3px;\n"
"}\n"
"")
        self.outputPart.setObjectName("outputPart")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.outputPart)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.outputPortSelector = QtWidgets.QComboBox(self.outputPart)
        self.outputPortSelector.setStyleSheet("QComboBox {\n"
"    background-color: #8ce1eb;\n"
"    border: 1px #26c6da;\n"
"    border-radius: 10px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    height: 20px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: rgb(34, 183, 199);\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(/Users/Kareem/Desktop/Task04DSP/icons/down-arrow.png);\n"
"    width: 20px; /* set the desired width */\n"
"    height: 20px; /* set the desired height */\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"    image: url(/Users/Kareem/Desktop/Task04DSP/icons/up-arrow.png);\n"
"    width: 20px; /* set the desired width */\n"
"    height: 20px; /* set the desired height */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 2px solid darkgray;\n"
"    selection-background-color: lightgray;\n"
"}")
        self.outputPortSelector.setObjectName("outputPortSelector")
        self.verticalLayout_2.addWidget(self.outputPortSelector)
        self.outputPortWidget = QtWidgets.QWidget(self.outputPart)
        self.outputPortWidget.setStyleSheet("QWidget {\n"
"    background-color: rgb(140, 225, 235);\n"
"}\n"
"")
        self.outputPortWidget.setObjectName("outputPortWidget")
        self.verticalLayout_2.addWidget(self.outputPortWidget)
        self.separatingLine = QtWidgets.QFrame(self.outputPart)
        self.separatingLine.setStyleSheet("")
        self.separatingLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.separatingLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.separatingLine.setObjectName("separatingLine")
        self.verticalLayout_2.addWidget(self.separatingLine)
        self.componentsMixer = QtWidgets.QGroupBox(self.outputPart)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        self.componentsMixer.setFont(font)
        self.componentsMixer.setObjectName("componentsMixer")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.componentsMixer)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.image01 = QtWidgets.QLabel(self.componentsMixer)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        self.image01.setFont(font)
        self.image01.setObjectName("image01")
        self.horizontalLayout_7.addWidget(self.image01)
        self.image01Slider = QtWidgets.QSlider(self.componentsMixer)
        self.image01Slider.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 1px solid #999999;\n"
"    height: 8px;\n"
"    background: rgb(140, 225, 235);\n"
"    margin: 2px 0;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(38, 198, 218);\n"
"    border: 1px solid #484848;\n"
"    width: 18px;\n"
"    margin: -2px 0;\n"
"    border-radius: 5px;\n"
"}")
        self.image01Slider.setOrientation(QtCore.Qt.Horizontal)
        self.image01Slider.setObjectName("image01Slider")
        self.horizontalLayout_7.addWidget(self.image01Slider)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.image02 = QtWidgets.QLabel(self.componentsMixer)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        self.image02.setFont(font)
        self.image02.setObjectName("image02")
        self.horizontalLayout_8.addWidget(self.image02)
        self.image02Slider = QtWidgets.QSlider(self.componentsMixer)
        self.image02Slider.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 1px solid #999999;\n"
"    height: 8px;\n"
"    background: rgb(140, 225, 235);\n"
"    margin: 2px 0;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(38, 198, 218);\n"
"    border: 1px solid #484848;\n"
"    width: 18px;\n"
"    margin: -2px 0;\n"
"    border-radius: 5px;\n"
"}")
        self.image02Slider.setOrientation(QtCore.Qt.Horizontal)
        self.image02Slider.setObjectName("image02Slider")
        self.horizontalLayout_8.addWidget(self.image02Slider)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.image03 = QtWidgets.QLabel(self.componentsMixer)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        self.image03.setFont(font)
        self.image03.setObjectName("image03")
        self.horizontalLayout_9.addWidget(self.image03)
        self.image03Slider = QtWidgets.QSlider(self.componentsMixer)
        self.image03Slider.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 1px solid #999999;\n"
"    height: 8px;\n"
"    background: rgb(140, 225, 235);\n"
"    margin: 2px 0;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(38, 198, 218);\n"
"    border: 1px solid #484848;\n"
"    width: 18px;\n"
"    margin: -2px 0;\n"
"    border-radius: 5px;\n"
"}")
        self.image03Slider.setOrientation(QtCore.Qt.Horizontal)
        self.image03Slider.setObjectName("image03Slider")
        self.horizontalLayout_9.addWidget(self.image03Slider)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.image04 = QtWidgets.QLabel(self.componentsMixer)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        self.image04.setFont(font)
        self.image04.setObjectName("image04")
        self.horizontalLayout_10.addWidget(self.image04)
        self.image04Slider = QtWidgets.QSlider(self.componentsMixer)
        self.image04Slider.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 1px solid #999999;\n"
"    height: 8px;\n"
"    background: rgb(140, 225, 235);\n"
"    margin: 2px 0;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(38, 198, 218);\n"
"    border: 1px solid #484848;\n"
"    width: 18px;\n"
"    margin: -2px 0;\n"
"    border-radius: 5px;\n"
"}")
        self.image04Slider.setOrientation(QtCore.Qt.Horizontal)
        self.image04Slider.setObjectName("image04Slider")
        self.horizontalLayout_10.addWidget(self.image04Slider)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.verticalLayout_2.addWidget(self.componentsMixer)
        self.horizontalLayout_11.addWidget(self.outputPart)
        self.gridLayout.addLayout(self.horizontalLayout_11, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setAutoFillBackground(False)
        self.toolBar.setStyleSheet("QToolBar {\n"
"    background: rgb(227, 248, 250);\n"
"    padding-right: 100px;\n"
"    spacing: 6px; /* spacing between items in the tool bar */\n"
"}")
        self.toolBar.setMovable(False)
        self.toolBar.setFloatable(True)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen_an_image = QtWidgets.QAction(MainWindow)
        self.actionOpen_an_image.setObjectName("actionOpen_an_image")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionRectangle_Selection = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/rectangle_selection_edited.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRectangle_Selection.setIcon(icon)
        self.actionRectangle_Selection.setObjectName("actionRectangle_Selection")
        self.actionDocumentation = QtWidgets.QAction(MainWindow)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.menuFile.addAction(self.actionOpen_an_image)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionRectangle_Selection)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.componentsMixer.setTitle(_translate("MainWindow", "Components Mixer"))
        self.image01.setText(_translate("MainWindow", "Image 01"))
        self.image02.setText(_translate("MainWindow", "Image 02"))
        self.image03.setText(_translate("MainWindow", "Image 03"))
        self.image04.setText(_translate("MainWindow", "Image 04"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen_an_image.setText(_translate("MainWindow", "Open an image"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionRectangle_Selection.setText(_translate("MainWindow", "Rectangle Selection"))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
